/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Nat,
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'accountType' : IDL.Text,
  'notes' : IDL.Text,
});
export const Budget = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'month' : IDL.Text,
  'limitAmount' : IDL.Float64,
  'spentAmount' : IDL.Float64,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const Debt = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'dueDate' : IDL.Int,
  'interestRate' : IDL.Float64,
  'remainingBalance' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'lender' : IDL.Text,
  'notes' : IDL.Text,
  'emiAmount' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'deadline' : IDL.Int,
  'targetAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'currentAmount' : IDL.Float64,
  'monthlyContribution' : IDL.Float64,
});
export const Investment = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'currentValue' : IDL.Float64,
  'notes' : IDL.Text,
  'investmentType' : IDL.Text,
  'amountInvested' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'transactionType' : IDL.Text,
  'accountId' : IDL.Nat,
  'source' : IDL.Text,
  'date' : IDL.Int,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CategorySpending = IDL.Record({
  'categoryId' : IDL.Nat,
  'totalSpent' : IDL.Float64,
});
export const MonthlySummary = IDL.Record({
  'totalIncome' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'savings' : IDL.Float64,
});
export const PortfolioSummary = IDL.Record({
  'totalProfitLoss' : IDL.Float64,
  'totalInvested' : IDL.Float64,
  'totalCurrentValue' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'contributeToGoal' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'createAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Account],
      [],
    ),
  'createBudget' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
      [Budget],
      [],
    ),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Category], []),
  'createDebt' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
      ],
      [Debt],
      [],
    ),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Float64, IDL.Text],
      [Goal],
      [],
    ),
  'createInvestment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Text],
      [Investment],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Int, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [Transaction],
      [],
    ),
  'deleteAccount' : IDL.Func([IDL.Nat], [], []),
  'deleteBudget' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteDebt' : IDL.Func([IDL.Nat], [], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllDebts' : IDL.Func([], [IDL.Vec(Debt)], ['query']),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getAllInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategorySpending' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CategorySpending)],
      ['query'],
    ),
  'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getTotalBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordDebtPayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferBetweenAccounts' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
  'updateAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Account],
      [],
    ),
  'updateBudget' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
      [Budget],
      [],
    ),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [Category],
      [],
    ),
  'updateDebt' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
      ],
      [Debt],
      [],
    ),
  'updateGoal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Float64,
        IDL.Text,
      ],
      [Goal],
      [],
    ),
  'updateInvestment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
      ],
      [Investment],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Int,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [Transaction],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Nat,
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'accountType' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Budget = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'month' : IDL.Text,
    'limitAmount' : IDL.Float64,
    'spentAmount' : IDL.Float64,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const Debt = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'dueDate' : IDL.Int,
    'interestRate' : IDL.Float64,
    'remainingBalance' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'lender' : IDL.Text,
    'notes' : IDL.Text,
    'emiAmount' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'deadline' : IDL.Int,
    'targetAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'currentAmount' : IDL.Float64,
    'monthlyContribution' : IDL.Float64,
  });
  const Investment = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'currentValue' : IDL.Float64,
    'notes' : IDL.Text,
    'investmentType' : IDL.Text,
    'amountInvested' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'transactionType' : IDL.Text,
    'accountId' : IDL.Nat,
    'source' : IDL.Text,
    'date' : IDL.Int,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CategorySpending = IDL.Record({
    'categoryId' : IDL.Nat,
    'totalSpent' : IDL.Float64,
  });
  const MonthlySummary = IDL.Record({
    'totalIncome' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'savings' : IDL.Float64,
  });
  const PortfolioSummary = IDL.Record({
    'totalProfitLoss' : IDL.Float64,
    'totalInvested' : IDL.Float64,
    'totalCurrentValue' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'contributeToGoal' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'createAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Account],
        [],
      ),
    'createBudget' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
        [Budget],
        [],
      ),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Category], []),
    'createDebt' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
        ],
        [Debt],
        [],
      ),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Float64, IDL.Text],
        [Goal],
        [],
      ),
    'createInvestment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Text],
        [Investment],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Int, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [Transaction],
        [],
      ),
    'deleteAccount' : IDL.Func([IDL.Nat], [], []),
    'deleteBudget' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteDebt' : IDL.Func([IDL.Nat], [], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllDebts' : IDL.Func([], [IDL.Vec(Debt)], ['query']),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getAllInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategorySpending' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CategorySpending)],
        ['query'],
      ),
    'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getTotalBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordDebtPayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferBetweenAccounts' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Account],
        [],
      ),
    'updateBudget' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
        [Budget],
        [],
      ),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [Category],
        [],
      ),
    'updateDebt' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
        ],
        [Debt],
        [],
      ),
    'updateGoal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Float64,
          IDL.Text,
        ],
        [Goal],
        [],
      ),
    'updateInvestment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
        ],
        [Investment],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Int,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [Transaction],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };