/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : bigint,
  'balance' : number,
  'name' : string,
  'accountType' : string,
  'notes' : string,
}
export interface Budget {
  'id' : bigint,
  'categoryId' : bigint,
  'month' : string,
  'limitAmount' : number,
  'spentAmount' : number,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'isDefault' : boolean,
}
export interface CategorySpending {
  'categoryId' : bigint,
  'totalSpent' : number,
}
export interface Debt {
  'id' : bigint,
  'name' : string,
  'dueDate' : bigint,
  'interestRate' : number,
  'remainingBalance' : number,
  'totalAmount' : number,
  'lender' : string,
  'notes' : string,
  'emiAmount' : number,
  'startDate' : bigint,
}
export interface Goal {
  'id' : bigint,
  'name' : string,
  'deadline' : bigint,
  'targetAmount' : number,
  'notes' : string,
  'currentAmount' : number,
  'monthlyContribution' : number,
}
export interface Investment {
  'id' : bigint,
  'date' : bigint,
  'name' : string,
  'currentValue' : number,
  'notes' : string,
  'investmentType' : string,
  'amountInvested' : number,
}
export interface MonthlySummary {
  'totalIncome' : number,
  'totalExpenses' : number,
  'savings' : number,
}
export interface PortfolioSummary {
  'totalProfitLoss' : number,
  'totalInvested' : number,
  'totalCurrentValue' : number,
}
export interface Transaction {
  'id' : bigint,
  'categoryId' : bigint,
  'transactionType' : string,
  'accountId' : bigint,
  'source' : string,
  'date' : bigint,
  'notes' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'contributeToGoal' : ActorMethod<[bigint, number], undefined>,
  'createAccount' : ActorMethod<[string, string, number, string], Account>,
  'createBudget' : ActorMethod<[bigint, string, number, number], Budget>,
  'createCategory' : ActorMethod<[string, string, boolean], Category>,
  'createDebt' : ActorMethod<
    [string, string, number, number, number, bigint, number, bigint, string],
    Debt
  >,
  'createGoal' : ActorMethod<
    [string, number, number, bigint, number, string],
    Goal
  >,
  'createInvestment' : ActorMethod<
    [string, string, number, number, bigint, string],
    Investment
  >,
  'createTransaction' : ActorMethod<
    [string, number, bigint, bigint, string, bigint, string],
    Transaction
  >,
  'deleteAccount' : ActorMethod<[bigint], undefined>,
  'deleteBudget' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteDebt' : ActorMethod<[bigint], undefined>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteInvestment' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBudgets' : ActorMethod<[], Array<Budget>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllDebts' : ActorMethod<[], Array<Debt>>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getAllInvestments' : ActorMethod<[], Array<Investment>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategorySpending' : ActorMethod<[string], Array<CategorySpending>>,
  'getMonthlySummary' : ActorMethod<[string], MonthlySummary>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getTotalBalance' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordDebtPayment' : ActorMethod<[bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferBetweenAccounts' : ActorMethod<[bigint, bigint, number], undefined>,
  'updateAccount' : ActorMethod<
    [bigint, string, string, number, string],
    Account
  >,
  'updateBudget' : ActorMethod<
    [bigint, bigint, string, number, number],
    Budget
  >,
  'updateCategory' : ActorMethod<[bigint, string, string, boolean], Category>,
  'updateDebt' : ActorMethod<
    [
      bigint,
      string,
      string,
      number,
      number,
      number,
      bigint,
      number,
      bigint,
      string,
    ],
    Debt
  >,
  'updateGoal' : ActorMethod<
    [bigint, string, number, number, bigint, number, string],
    Goal
  >,
  'updateInvestment' : ActorMethod<
    [bigint, string, string, number, number, bigint, string],
    Investment
  >,
  'updateTransaction' : ActorMethod<
    [bigint, string, number, bigint, bigint, string, bigint, string],
    Transaction
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];